name: Release
on:
  push:
    branches:
    - master
jobs:
  docker_release:
    name: Docker Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: One Click Docker
      uses: pangzineng/Github-Action-One-Click-Docker@v1.1.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_NAMESPACE: jakewalker
